"use client"

import type React from "react"

import { createContext, useContext, useState, useEffect } from "react"

type Language = "ru" | "en" | "zh" | "ar"

interface Translations {
  [key: string]: {
    [key: string]: string | { [key: string]: string }
  }
}

const translations: Record<Language, Translations> = {
  ru: {
    nav: {
      map: "Карта",
      favorites: "Избранное",
      tours: "Туры и Места",
      chat: "Чат",
      history: "История",
      profile: "Профиль",
    },
    map: {
      searchPlaceholder: "Поиск мест...",
      all: "Все",
      noPlaces: "Нет мест",
      noResults: "Нет результатов",
      filterByCity: "Фильтр по городам",
      addToCart: "Добавить",
      removeFromCart: "Удалить",
      createTour: "Создать тур",
      list: "Список",
      map: "Карта",
      route: "Маршрут",
      customTour: "Пользовательский тур с",
      places: "местами",
      createNewTour: "Создать новый тур",
      tourName: "Название тура",
      create: "Создать",
      cancel: "Отмена",
      selectPlaces: "Выберите места",
      calculateRoute: "Рассчитать маршрут",
      routeView: "Просмотр маршрута",
    },
    tours: {
      title: "Туры и Места",
      subtitle: "Откройте лучшие туры по Узбекистану",
      activeTours: "Действующие туры",
      allTours: "Все туры",
      myTours: "Мои туры",
      history: "История",
      searchTours: "Поиск туров...",
      filterByCity: "Фильтр по городам",
      allCities: "Все города",
      hours: "часов",
      participants: "участников",
      noToursFound: "Туры не найдены",
      manageTour: "Управлять туром",
      noCreatedTours: "У вас нет созданных туров",
      createNew: "Создать новый тур",
      spent: "Потрачено",
      emptyHistory: "История туров пуста",
      noActiveTours: "У вас нет активных туров",
      difficulty: "Сложность",
      price: "Цена",
      duration: "Продолжительность",
      maxParticipants: "Максимум участников",
      currentParticipants: "Текущие участники",
    },
    welcome: {
      tagline: "Ваш AI помощник для путешествий ✈️",
      title: "Откройте для себя\nУзбекистан",
      description: "Персонализированные рекомендации, умный маршрутизатор и местные секреты - все в одном месте",
      startJourney: "Начать путешествие",
      login: "Войти",
    },
    onboarding: {
      selectInterests: "Выберите ваши интересы",
      selectCity: "Выберите город",
      next: "Далее",
      continue: "Продолжить",
      welcome: "Добро пожаловать в WayZen",
      selectOneOrMore: "Выберите одну или несколько категорий",
      uzbekCities: "Города Узбекистана",
      selectOneCity: "Выберите один город для начала",
      whereToGo: "Куда вы хотите отправиться? Мы будем рекомендовать туры и места в выбранном городе",
      back: "Назад",
      saving: "Сохранение...",
    },
    favorites: {
      title: "Избранное",
      places: "Места",
      place: "место",
      tours: "Туры",
      filterByCategory: "Фильтр по категориям",
      filterByCity: "Фильтр по городам",
      noFavorites: "Нет избранных",
      empty: "Нет избранных",
      emptyDescription: "Добавляйте места и туры в избранное, чтобы сохранить их для позже",
      explore: "Исследовать",
    },
    profile: {
      myProfile: "Мой профиль",
      settings: "Настройки",
      language: "Язык",
      logout: "Выход",
      about: "О нас",
    },
    about: {
      title: "О WayZen",
      description: "WayZen - это ваш персональный AI помощник для путешествий по Узбекистану",
      features: "Особенности",
      feature1: "Персонализированные рекомендации",
      feature2: "Умный маршрутизатор",
      feature3: "Мониторинг цен",
      feature4: "Поделиться маршрутами",
    },
    home: {
      viewAllLocations: "Просмотреть все места",
      loading: "Загрузка рекомендаций...",
      noRecommendations: "Нет рекомендаций",
      recommendations: "Рекомендации для вас",
      topPlaces: "Лучшие места",
      topTours: "Лучшие туры",
    },
    cities: {
      tashkent: "Ташкент",
      samarkand: "Самарканд",
      bukhara: "Бухара",
      khiva: "Хива",
      fergona: "Фергона",
      kokand: "Коканд",
      shahrisabz: "Шахрисабз",
      andijan: "Андижан",
      namangan: "Наманган",
      nukus: "Нукус",
    },
    categories: {
      sport: "Спорт",
      culture: "Культура и история",
      nature: "Природа",
      crafts: "Ремесленничество",
      travel: "Путешествия",
      entertainment: "Развлечения",
      food: "Еда",
    },
    auth: {
      login: "Вход в ECHO",
      signup: "Регистрация",
      enterEmail: "Введите ваш email для входа",
      email: "Email",
      password: "Пароль",
      forgotPassword: "Забыли пароль?",
      loggingIn: "Вход...",
      noAccount: "Нет аккаунта?",
      createAccount: "Создайте аккаунт, чтобы начать путешествие",
      name: "Имя",
      yourName: "Ваше имя",
      signingUp: "Регистрация...",
      haveAccount: "Уже есть аккаунт?",
    },
    history: {
      title: "История",
      noChats: "История туров пуста",
      empty: "Нет истории",
      emptyDescription: "Туры, которые вы посещали, будут отображаться здесь",
    },
    chat: {
      title: "Чат",
      placeholder: "Напишите вашу задачу",
      send: "Отправить",
      noChats: "Нет чатов",
    },
  },
  en: {
    nav: {
      map: "Map",
      favorites: "Favorites",
      tours: "Tours & Places",
      chat: "Chat",
      history: "History",
      profile: "Profile",
    },
    map: {
      searchPlaceholder: "Search places...",
      all: "All",
      noPlaces: "No places",
      noResults: "No results",
      filterByCity: "Filter by city",
      addToCart: "Add",
      removeFromCart: "Remove",
      createTour: "Create tour",
      list: "List",
      map: "Map",
      route: "Route",
      customTour: "Custom tour with",
      places: "places",
      createNewTour: "Create New Tour",
      tourName: "Tour name",
      create: "Create",
      cancel: "Cancel",
      selectPlaces: "Select places",
      calculateRoute: "Calculate route",
      routeView: "Route view",
    },
    tours: {
      title: "Tours & Places",
      subtitle: "Discover the best tours in Uzbekistan",
      activeTours: "Active Tours",
      allTours: "All Tours",
      myTours: "My Tours",
      history: "History",
      searchTours: "Search tours...",
      filterByCity: "Filter by city",
      allCities: "All cities",
      hours: "hours",
      participants: "participants",
      noToursFound: "No tours found",
      manageTour: "Manage Tour",
      noCreatedTours: "You have no created tours",
      createNew: "Create New Tour",
      spent: "Spent",
      emptyHistory: "Tour history is empty",
      noActiveTours: "You have no active tours",
      difficulty: "Difficulty",
      price: "Price",
      duration: "Duration",
      maxParticipants: "Max participants",
      currentParticipants: "Current participants",
    },
    welcome: {
      tagline: "Your AI travel assistant ✈️",
      title: "Discover\nUzbekistan",
      description: "Personalized recommendations, smart routing and local secrets - all in one place",
      startJourney: "Start Journey",
      login: "Login",
    },
    onboarding: {
      selectInterests: "Select your interests",
      selectCity: "Select city",
      next: "Next",
      continue: "Continue",
      welcome: "Welcome to WayZen",
      selectOneOrMore: "Select one or more categories",
      uzbekCities: "Cities of Uzbekistan",
      selectOneCity: "Select one city to start",
      whereToGo: "Where do you want to go? We will recommend tours and places in your selected city",
      back: "Back",
      saving: "Saving...",
    },
    favorites: {
      title: "Favorites",
      places: "Places",
      place: "place",
      tours: "Tours",
      filterByCategory: "Filter by category",
      filterByCity: "Filter by city",
      noFavorites: "No favorites",
      empty: "No favorites",
      emptyDescription: "Add places and tours to favorites to save them for later",
      explore: "Explore",
    },
    profile: {
      myProfile: "My Profile",
      settings: "Settings",
      language: "Language",
      logout: "Logout",
      about: "About",
    },
    about: {
      title: "About WayZen",
      description: "WayZen is your personal AI travel assistant for exploring Uzbekistan",
      features: "Features",
      feature1: "Personalized recommendations",
      feature2: "Smart routing",
      feature3: "Price monitoring",
      feature4: "Share routes",
    },
    home: {
      viewAllLocations: "View all locations",
      loading: "Loading recommendations...",
      noRecommendations: "No recommendations",
      recommendations: "Recommendations for you",
      topPlaces: "Top places",
      topTours: "Top tours",
    },
    cities: {
      tashkent: "Tashkent",
      samarkand: "Samarkand",
      bukhara: "Bukhara",
      khiva: "Khiva",
      fergona: "Fergona",
      kokand: "Kokand",
      shahrisabz: "Shahrisabz",
      andijan: "Andijan",
      namangan: "Namangan",
      nukus: "Nukus",
    },
    categories: {
      sport: "Sport",
      culture: "Culture & History",
      nature: "Nature",
      crafts: "Crafts",
      travel: "Travel",
      entertainment: "Entertainment",
      food: "Food",
    },
    auth: {
      login: "Login to ECHO",
      signup: "Sign Up",
      enterEmail: "Enter your email to login",
      email: "Email",
      password: "Password",
      forgotPassword: "Forgot password?",
      loggingIn: "Logging in...",
      noAccount: "Don't have an account?",
      createAccount: "Create an account to start your journey",
      name: "Name",
      yourName: "Your name",
      signingUp: "Signing up...",
      haveAccount: "Already have an account?",
    },
    history: {
      title: "History",
      noChats: "Tour history is empty",
      empty: "No history",
      emptyDescription: "Tours you visited will appear here",
    },
    chat: {
      title: "Chat",
      placeholder: "Describe your task",
      send: "Send",
      noChats: "No chats",
    },
  },
  zh: {
    nav: {
      map: "地图",
      favorites: "收藏",
      tours: "旅游和地点",
      chat: "聊天",
      history: "历史",
      profile: "个人资料",
    },
    map: {
      searchPlaceholder: "搜索地点...",
      all: "全部",
      noPlaces: "没有地点",
      noResults: "没有结果",
      filterByCity: "按城市筛选",
      addToCart: "添加",
      removeFromCart: "删除",
      createTour: "创建旅游",
      list: "列表",
      map: "地图",
      route: "路线",
      customTour: "自定义旅游",
      places: "地点",
      createNewTour: "创建新旅游",
      tourName: "旅游名称",
      create: "创建",
      cancel: "取消",
      selectPlaces: "选择地点",
      calculateRoute: "计算路线",
      routeView: "路线视图",
    },
    tours: {
      title: "旅游和地点",
      subtitle: "发现乌兹别克斯坦最好的旅游",
      activeTours: "活跃旅游",
      allTours: "所有旅游",
      myTours: "我的旅游",
      history: "历史",
      searchTours: "搜索旅游...",
      filterByCity: "按城市筛选",
      allCities: "所有城市",
      hours: "小时",
      participants: "参与者",
      noToursFound: "未找到旅游",
      manageTour: "管理旅游",
      noCreatedTours: "您没有创建的旅游",
      createNew: "创建新旅游",
      spent: "花费",
      emptyHistory: "旅游历史为空",
      noActiveTours: "您没有活跃旅游",
      difficulty: "难度",
      price: "价格",
      duration: "持续时间",
      maxParticipants: "最大参与者",
      currentParticipants: "当前参与者",
    },
    welcome: {
      tagline: "您的人工智能旅行助手 ✈️",
      title: "发现\n乌兹别克斯坦",
      description: "个性化推荐、智能路由和本地秘密 - 一切尽在一处",
      startJourney: "开始旅程",
      login: "登录",
    },
    onboarding: {
      selectInterests: "选择您的兴趣",
      selectCity: "选择城市",
      next: "下一步",
      continue: "继续",
      welcome: "欢迎来到 WayZen",
      selectOneOrMore: "选择一个或多个类别",
      uzbekCities: "乌兹别克斯坦城市",
      selectOneCity: "选择一个城市开始",
      whereToGo: "您想去哪里？我们将推荐您选择的城市中的旅游和地点",
      back: "返回",
      saving: "保存中...",
    },
    favorites: {
      title: "收藏",
      places: "地点",
      place: "地点",
      tours: "旅游",
      filterByCategory: "按类别筛选",
      filterByCity: "按城市筛选",
      noFavorites: "没有收藏",
      empty: "没有收藏",
      emptyDescription: "添加地点和旅游到收藏以供以后使用",
      explore: "探索",
    },
    profile: {
      myProfile: "我的个人资料",
      settings: "设置",
      language: "语言",
      logout: "登出",
      about: "关于",
    },
    about: {
      title: "关于 WayZen",
      description: "WayZen 是您探索乌兹别克斯坦的个人人工智能旅行助手",
      features: "特征",
      feature1: "个性化推荐",
      feature2: "智能路由",
      feature3: "价格监控",
      feature4: "分享路线",
    },
    home: {
      viewAllLocations: "查看所有地点",
      loading: "加载推荐...",
      noRecommendations: "没有推荐",
      recommendations: "为您推荐",
      topPlaces: "热门地点",
      topTours: "热门旅游",
    },
    cities: {
      tashkent: "塔什干",
      samarkand: "撒马尔罕",
      bukhara: "布哈拉",
      khiva: "希瓦",
      fergona: "费尔干纳",
      kokand: "浩罕",
      shahrisabz: "沙赫里萨布兹",
      andijan: "安集延",
      namangan: "纳曼干",
      nukus: "努库斯",
    },
    categories: {
      sport: "运动",
      culture: "文化和历史",
      nature: "自然",
      crafts: "工艺",
      travel: "旅游",
      entertainment: "娱乐",
      food: "食物",
    },
    auth: {
      login: "登录 ECHO",
      signup: "注册",
      enterEmail: "输入您的电子邮件以登录",
      email: "电子邮件",
      password: "密码",
      forgotPassword: "忘记密码？",
      loggingIn: "正在登录...",
      noAccount: "没有账户？",
      createAccount: "创建账户以开始您的旅程",
      name: "名字",
      yourName: "您的名字",
      signingUp: "正在注册...",
      haveAccount: "已有账户？",
    },
    history: {
      title: "历史",
      noChats: "旅游历史为空",
      empty: "没有历史",
      emptyDescription: "您访问的旅游将显示在这里",
    },
    chat: {
      title: "聊天",
      placeholder: "描述您的任务",
      send: "发送",
      noChats: "没有聊天",
    },
  },
  ar: {
    nav: {
      map: "الخريطة",
      favorites: "المفضلة",
      tours: "الجولات والأماكن",
      chat: "الدردشة",
      history: "السجل",
      profile: "الملف الشخصي",
    },
    map: {
      searchPlaceholder: "البحث عن الأماكن...",
      all: "الكل",
      noPlaces: "لا توجد أماكن",
      noResults: "لا توجد نتائج",
      filterByCity: "تصفية حسب المدينة",
      addToCart: "إضافة",
      removeFromCart: "إزالة",
      createTour: "إنشاء جولة",
      list: "قائمة",
      map: "الخريطة",
      route: "المسار",
      customTour: "جولة مخصصة",
      places: "أماكن",
      createNewTour: "إنشاء جولة جديدة",
      tourName: "اسم الجولة",
      create: "إنشاء",
      cancel: "إلغاء",
      selectPlaces: "اختر الأماكن",
      calculateRoute: "حساب المسار",
      routeView: "عرض المسار",
    },
    tours: {
      title: "الجولات والأماكن",
      subtitle: "اكتشف أفضل الجولات في أوزبكستان",
      activeTours: "الجولات النشطة",
      allTours: "جميع الجولات",
      myTours: "جولاتي",
      history: "السجل",
      searchTours: "البحث عن الجولات...",
      filterByCity: "تصفية حسب المدينة",
      allCities: "جميع المدن",
      hours: "ساعات",
      participants: "المشاركون",
      noToursFound: "لم يتم العثور على جولات",
      manageTour: "إدارة الجولة",
      noCreatedTours: "ليس لديك جولات تم إنشاؤها",
      createNew: "إنشاء جولة جديدة",
      spent: "تم الإنفاق",
      emptyHistory: "سجل الجولات فارغ",
      noActiveTours: "ليس لديك جولات نشطة",
      difficulty: "الصعوبة",
      price: "السعر",
      duration: "المدة",
      maxParticipants: "الحد الأقصى للمشاركين",
      currentParticipants: "المشاركون الحاليون",
    },
    welcome: {
      tagline: "مساعدك الذكي للسفر ✈️",
      title: "اكتشف\nأوزبكستان",
      description: "توصيات مخصصة وتوجيه ذكي وأسرار محلية - كل شيء في مكان واحد",
      startJourney: "ابدأ الرحلة",
      login: "تسجيل الدخول",
    },
    onboarding: {
      selectInterests: "اختر اهتماماتك",
      selectCity: "اختر المدينة",
      next: "التالي",
      continue: "متابعة",
      welcome: "أهلا وسهلا في WayZen",
      selectOneOrMore: "اختر فئة واحدة أو أكثر",
      uzbekCities: "مدن أوزبكستان",
      selectOneCity: "اختر مدينة واحدة للبدء",
      whereToGo: "أين تريد أن تذهب؟ سنوصي بالجولات والأماكن في المدينة المختارة",
      back: "رجوع",
      saving: "جاري الحفظ...",
    },
    favorites: {
      title: "المفضلة",
      places: "الأماكن",
      place: "مكان",
      tours: "الجولات",
      filterByCategory: "تصفية حسب الفئة",
      filterByCity: "تصفية حسب المدينة",
      noFavorites: "لا توجد مفضلة",
      empty: "لا توجد مفضلة",
      emptyDescription: "أضف الأماكن والجولات إلى المفضلة لحفظها لاحقاً",
      explore: "استكشف",
    },
    profile: {
      myProfile: "ملفي الشخصي",
      settings: "الإعدادات",
      language: "اللغة",
      logout: "تسجيل الخروج",
      about: "حول",
    },
    about: {
      title: "حول WayZen",
      description: "WayZen هو مساعدك الشخصي الذكي للسفر لاستكشاف أوزبكستان",
      features: "الميزات",
      feature1: "توصيات مخصصة",
      feature2: "التوجيه الذكي",
      feature3: "مراقبة الأسعار",
      feature4: "مشاركة المسارات",
    },
    home: {
      viewAllLocations: "عرض جميع الأماكن",
      loading: "جاري تحميل التوصيات...",
      noRecommendations: "لا توجد توصيات",
      recommendations: "التوصيات لك",
      topPlaces: "أفضل الأماكن",
      topTours: "أفضل الجولات",
    },
    cities: {
      tashkent: "طشقند",
      samarkand: "سمرقند",
      bukhara: "بخارى",
      khiva: "خيوة",
      fergona: "فرغانة",
      kokand: "خوقند",
      shahrisabz: "شهرسبز",
      andijan: "أنديجان",
      namangan: "نمنجان",
      nukus: "نوكوس",
    },
    categories: {
      sport: "رياضة",
      culture: "الثقافة والتاريخ",
      nature: "الطبيعة",
      crafts: "الحرف اليدوية",
      travel: "السفر",
      entertainment: "الترفيه",
      food: "الطعام",
    },
    auth: {
      login: "تسجيل الدخول إلى ECHO",
      signup: "إنشاء حساب",
      enterEmail: "أدخل بريدك الإلكتروني لتسجيل الدخول",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      forgotPassword: "هل نسيت كلمة المرور؟",
      loggingIn: "جاري تسجيل الدخول...",
      noAccount: "ليس لديك حساب؟",
      createAccount: "أنشئ حسابًا لبدء رحلتك",
      name: "الاسم",
      yourName: "اسمك",
      signingUp: "جاري التسجيل...",
      haveAccount: "هل لديك حساب بالفعل؟",
    },
    history: {
      title: "السجل",
      noChats: "سجل الجولات فارغ",
      empty: "لا يوجد سجل",
      emptyDescription: "ستظهر الجولات التي زرتها هنا",
    },
    chat: {
      title: "الدردشة",
      placeholder: "صف مهمتك",
      send: "إرسال",
      noChats: "لا توجد دردشات",
    },
  },
}

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("ru")
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    const saved = localStorage.getItem("language") as Language | null
    if (saved && ["ru", "en", "zh", "ar"].includes(saved)) {
      setLanguageState(saved)
    }
    setMounted(true)
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem("language", lang)
  }

  const t = (key: string): string => {
    const keys = key.split(".")
    let value: any = translations[language]

    for (const k of keys) {
      value = value?.[k]
    }

    return typeof value === "string" ? value : key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider")
  }
  return context
}
