import type { Category, Tour, Place } from "./types"

export const categories: Category[] = [
  {
    id: "sport",
    name: "Спорт",
    icon: "⚽",
    description: "Спортивные площадки и активности",
  },
  {
    id: "culture",
    name: "Культура и история",
    icon: "🏛️",
    description: "Исторические места и культурные достопримечательности",
  },
  {
    id: "nature",
    name: "Природа",
    icon: "🌿",
    description: "Природные парки и живописные места",
  },
  {
    id: "crafts",
    name: "Ремесленничество",
    icon: "🎨",
    description: "Мастерские и ремесленные центры",
  },
  {
    id: "travel",
    name: "Путешествия",
    icon: "✈️",
    description: "Туристические маршруты и экскурсии",
  },
  {
    id: "entertainment",
    name: "Развлечения",
    icon: "🎭",
    description: "Развлекательные центры и мероприятия",
  },
  {
    id: "food",
    name: "Еда",
    icon: "🍽️",
    description: "Рестораны и традиционная кухня",
  },
]

export const mockTours: Tour[] = [
  {
    id: "tour-1",
    name: "Исторический Самарканд",
    description: "Полный день в древнем городе Самарканда с посещением главных достопримечательностей",
    city: "Самарканд",
    places: ["p_culture_1", "p_culture_5", "p_culture_8"],
    duration: 8,
    price: 45,
    estimatedCost: 120,
    difficulty: "easy",
    rating: 4.8,
    reviewCount: 234,
    image: "/samarkand-historic-tour.jpg",
    tags: ["история", "культура", "экскурсия"],
    createdBy: "admin",
    createdAt: new Date().toISOString(),
    isActive: true,
    maxParticipants: 20,
    currentParticipants: 12,
    route: ["Регистан", "Мавзолей Гур-Эмир", "Обсерватория Улугбека"],
    isCustom: false,
    priceHistory: [],
    expenses: [],
  },
  {
    id: "tour-2",
    name: "Древняя Бухара",
    description: "Путешествие по Шелковому пути с посещением медресе и базаров",
    city: "Бухара",
    places: ["p_culture_4", "p_culture_9", "p_food_4"],
    duration: 7,
    price: 40,
    estimatedCost: 100,
    difficulty: "easy",
    rating: 4.7,
    reviewCount: 189,
    image: "/bukhara-ancient-city.jpg",
    tags: ["история", "базар", "культура"],
    createdBy: "admin",
    createdAt: new Date().toISOString(),
    isActive: true,
    maxParticipants: 15,
    currentParticipants: 8,
    route: ["Крепость Арк", "Минарет Калон", "Чайхана Лаби-Хауз"],
    isCustom: false,
    priceHistory: [],
    expenses: [],
  },
  {
    id: "tour-3",
    name: "Хива - город-музей",
    description: "Экскурсия по хорошо сохранившемуся средневековому городу",
    city: "Хива",
    places: ["p_culture_7", "p_craft_6", "p_food_10"],
    duration: 6,
    price: 35,
    estimatedCost: 85,
    difficulty: "easy",
    rating: 4.9,
    reviewCount: 156,
    image: "/khiva-medieval-city.jpg",
    tags: ["история", "архитектура", "музей"],
    createdBy: "admin",
    createdAt: new Date().toISOString(),
    isActive: true,
    maxParticipants: 12,
    currentParticipants: 10,
    route: ["Крепость Ичан-Кала", "Мечеть Джума", "Дворец Таш-Хаули"],
    isCustom: false,
    priceHistory: [],
    expenses: [],
  },
  {
    id: "tour-4",
    name: "Ташкент - столица Узбекистана",
    description: "Современный Ташкент: музеи, парки и национальная архитектура",
    city: "Ташкент",
    places: ["p_culture_6", "p_entertainment_1", "p_food_1"],
    duration: 5,
    price: 30,
    estimatedCost: 75,
    difficulty: "easy",
    rating: 4.6,
    reviewCount: 267,
    image: "/tashkent-capital-city.jpg",
    tags: ["современность", "музеи", "архитектура"],
    createdBy: "admin",
    createdAt: new Date().toISOString(),
    isActive: true,
    maxParticipants: 25,
    currentParticipants: 18,
    route: ["Площадь Независимости", "Комплекс Хазрати Имам", "Базар Чорсу"],
    isCustom: false,
    priceHistory: [],
    expenses: [],
  },
]

export const mockPlaces: Place[] = [
  {
    id: "p_culture_1",
    name: "Регистан",
    description: "Величественный комплекс медресе с голубыми куполами",
    city: "Самарканд",
    categoryId: "culture",
    rating: 4.9,
    reviewCount: 512,
    images: ["/registan.jpg"],
    tags: ["архитектура", "история", "медресе"],
    coordinates: { lat: 39.6548, lng: 66.9746 },
  },
  {
    id: "p_culture_4",
    name: "Крепость Арк",
    description: "Древняя крепость в центре Бухары",
    city: "Бухара",
    categoryId: "culture",
    rating: 4.7,
    reviewCount: 389,
    images: ["/ark-fortress.jpg"],
    tags: ["крепость", "история", "архитектура"],
    coordinates: { lat: 39.7747, lng: 64.4161 },
  },
  {
    id: "p_culture_5",
    name: "Мавзолей Гур-Эмир",
    description: "Мавзолей Тимура с красивой архитектурой",
    city: "Самарканд",
    categoryId: "culture",
    rating: 4.8,
    reviewCount: 456,
    images: ["/gur-emir.jpg"],
    tags: ["мавзолей", "история", "архитектура"],
    coordinates: { lat: 39.6548, lng: 66.9746 },
  },
  {
    id: "p_culture_6",
    name: "Площадь Независимости",
    description: "Главная площадь Ташкента с памятниками",
    city: "Ташкент",
    categoryId: "culture",
    rating: 4.6,
    reviewCount: 678,
    images: ["/independence-square.jpg"],
    tags: ["площадь", "памятник", "современность"],
    coordinates: { lat: 41.2995, lng: 69.2401 },
  },
  {
    id: "p_culture_7",
    name: "Крепость Ичан-Кала",
    description: "Внутренняя крепость Хивы с древними стенами",
    city: "Хива",
    categoryId: "culture",
    rating: 4.9,
    reviewCount: 423,
    images: ["/ichan-kala.jpg"],
    tags: ["крепость", "история", "музей"],
    coordinates: { lat: 41.3783, lng: 61.3794 },
  },
  {
    id: "p_culture_8",
    name: "Обсерватория Улугбека",
    description: "Древняя обсерватория с научными инструментами",
    city: "Самарканд",
    categoryId: "culture",
    rating: 4.7,
    reviewCount: 334,
    images: ["/ulugbek-observatory.jpg"],
    tags: ["наука", "история", "архитектура"],
    coordinates: { lat: 39.6548, lng: 66.9746 },
  },
  {
    id: "p_culture_9",
    name: "Минарет Калон",
    description: "Высокий минарет с видом на город",
    city: "Бухара",
    categoryId: "culture",
    rating: 4.8,
    reviewCount: 401,
    images: ["/kalon-minaret.jpg"],
    tags: ["минарет", "история", "архитектура"],
    coordinates: { lat: 39.7747, lng: 64.4161 },
  },
  {
    id: "p_entertainment_1",
    name: "Комплекс Хазрати Имам",
    description: "Религиозный комплекс с мечетью и медресе",
    city: "Ташкент",
    categoryId: "entertainment",
    rating: 4.5,
    reviewCount: 289,
    images: ["/hazrati-imam.jpg"],
    tags: ["мечеть", "религия", "архитектура"],
    coordinates: { lat: 41.2995, lng: 69.2401 },
  },
  {
    id: "p_food_1",
    name: "Базар Чорсу",
    description: "Традиционный восточный базар с едой и товарами",
    city: "Ташкент",
    categoryId: "food",
    rating: 4.6,
    reviewCount: 567,
    images: ["/chorsu-bazaar.jpg"],
    tags: ["базар", "еда", "торговля"],
    coordinates: { lat: 41.2995, lng: 69.2401 },
  },
  {
    id: "p_food_4",
    name: "Чайхана Лаби-Хауз",
    description: "Традиционная чайхана с узбекской кухней",
    city: "Бухара",
    categoryId: "food",
    rating: 4.7,
    reviewCount: 445,
    images: ["/labi-hauz.jpg"],
    tags: ["еда", "традиция", "чайхана"],
    coordinates: { lat: 39.7747, lng: 64.4161 },
  },
  {
    id: "p_food_10",
    name: "Плов-хана",
    description: "Ресторан с традиционным узбекским пловом",
    city: "Хива",
    categoryId: "food",
    rating: 4.8,
    reviewCount: 312,
    images: ["/plov-khana.jpg"],
    tags: ["еда", "плов", "традиция"],
    coordinates: { lat: 41.3783, lng: 61.3794 },
  },
  {
    id: "p_craft_6",
    name: "Мастерская керамики",
    description: "Традиционная мастерская по изготовлению керамики",
    city: "Хива",
    categoryId: "crafts",
    rating: 4.6,
    reviewCount: 278,
    images: ["/ceramic-workshop.jpg"],
    tags: ["ремесло", "керамика", "традиция"],
    coordinates: { lat: 41.3783, lng: 61.3794 },
  },
]
